In [2]:
# Numpy 
import numpy as np

In [25]:
 
myarr=np.array([[3,6,32,7],
               [1,2,3,4]],np.int32) #it is 2d array

In [26]:
myarr                     

array([[ 3,  6, 32,  7],
       [ 1,  2,  3,  4]])

In [27]:
myarr[0,3] # [row,cols]

7

In [28]:
myarr.shape # it gives the shape of an array

(2, 4)

In [29]:
myarr.dtype # it tells the data type of array

dtype('int32')

In [30]:
myarr.ndim

2

In [34]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [36]:
rng=np.arange(15)

In [37]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [38]:
lspace=np.linspace(1,50,10)

In [39]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [40]:
emp=np.empty((4,6))

In [41]:
emp

array([[1.39197060e-311, 1.39197061e-311, 1.39197061e-311,
        1.39197061e-311, 1.39197061e-311, 1.39197061e-311],
       [1.39197061e-311, 1.39197061e-311, 1.39197061e-311,
        1.39197060e-311, 1.39197061e-311, 1.39197061e-311],
       [1.39197061e-311, 1.39197060e-311, 1.39197061e-311,
        1.39197061e-311, 1.39197060e-311, 1.39197060e-311],
       [1.39197061e-311, 1.05700515e-307, 2.04712906e-306,
        7.56589622e-307, 1.11258277e-307, 8.90111708e-307]])

In [44]:
 ide=np.identity(45)

In [45]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [47]:
arr=np.arange(99)

In [49]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [52]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [53]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [54]:
arr.shape

(99,)

In [55]:
# numpy axis
x=[[1,2,3],[4,5,6],[7,1,0]]

In [56]:
ar=np.array(x)

In [58]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [57]:
ar.sum(axis=0)

array([12,  8,  9])

In [59]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [60]:
ar.T #Transpose

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [61]:
ar.flat

In [63]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [64]:
ar.argmin()

8

In [65]:
ar.argmax()

6

In [68]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [70]:
np.where(ar>5) # it tells where ar value is greater than 5 hai

(array([1, 2], dtype=int64), array([2, 2], dtype=int64))

In [71]:
type(np.where(ar>5))

tuple

In [79]:
ar * ar * ar

array([[  1,   8,  27],
       [ 64, 125, 216],
       [  0,   1, 343]])

In [80]:
newarr=ar+ar

In [81]:
ar-newarr

array([[-1, -2, -3],
       [-4, -5, -6],
       [ 0, -1, -7]])