In [2]:
# Numpy 
import numpy as np

In [25]:
 
myarr=np.array([[3,6,32,7],
               [1,2,3,4]],np.int32) #it is 2d array

In [26]:
myarr                     

array([[ 3,  6, 32,  7],
       [ 1,  2,  3,  4]])

In [27]:
myarr[0,3] # [row,cols]

7

In [28]:
myarr.shape # it gives the shape of an array

(2, 4)

In [29]:
myarr.dtype # it tells the data type of array

dtype('int32')

In [30]:
myarr.ndim

2

In [34]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [36]:
rng=np.arange(15)

In [37]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [38]:
lspace=np.linspace(1,50,10)

In [39]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [40]:
emp=np.empty((4,6))

In [41]:
emp

array([[1.39197060e-311, 1.39197061e-311, 1.39197061e-311,
        1.39197061e-311, 1.39197061e-311, 1.39197061e-311],
       [1.39197061e-311, 1.39197061e-311, 1.39197061e-311,
        1.39197060e-311, 1.39197061e-311, 1.39197061e-311],
       [1.39197061e-311, 1.39197060e-311, 1.39197061e-311,
        1.39197061e-311, 1.39197060e-311, 1.39197060e-311],
       [1.39197061e-311, 1.05700515e-307, 2.04712906e-306,
        7.56589622e-307, 1.11258277e-307, 8.90111708e-307]])